repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.253'
  hooks:
  - id: ruff
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.296
  hooks:
  - id: pyright
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.7.0
  hooks:
  - id: isort
- repo: https://github.com/yunojuno/pre-commit-xenon
  rev: cc59b0431a5d072786b59430e9b342b2881064f6
  hooks:
  - id: xenon
    args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]